### ISSUE TITLE
no file 's2eta.lua')

### ISSUE THREAD

**Issue by rlust** [mrkale/NodeMCU-WifiDoubleSwitch#1]
This looks like a great application!
I have gotten to the point that when I try to open a web page  I get an error:

PANIC: unprotected error in call to Lua API (module 's2eta' not found:
    no field package.preload['s2eta']
    no file 's2eta.lc'
    no file 's2eta.lua')
Where is this file?

Thanks

**Comment by mrkale** [comment]
All modules used in the web server (nistclock, s2eta) there are in my repository [NodeMCU-Modules](https://github.com/mrkale/NodeMCU-Modules).

**Comment by rlust** [comment]
I have loaded the most recent firmware with integer support and still getting this error when running init.la

init.lua:141: attempt to index global 'nistclock' (a nil value)
stack traceback:
    init.lua:141: in main chunk
    [C]: in function 'dofile'
    stdin:1: in main chunk
Any ideas?
Thanks

**Comment by mrkale** [comment]
You have not uploaded the [nistclock.lua](https://github.com/mrkale/NodeMCU-Modules/tree/master/nistclock) module to your devkit.
