### ISSUE TITLE
get HttpHeader error

### ISSUE THREAD

**Issue by rlust** [mrkale/NodeMCU-WifiDoubleSwitch#2]
I found and loaded the s2eta.lua module, and got by that error.

Not when I try web page I get the following error:

PANIC: unprotected error in call to Lua API (?:0: attempt to call global 'getHttpHeader' (a nil value))
�!sBt���!��1�)�vc�����

NodeMCU custom build by frightanic.com
    branch: master
    commit: c8037568571edb5c568c2f8231e4f8ce0683b883
    SSL: false
    modules: node,file,gpio,wifi,net,pwm,tmr,uart,ow,mqtt
 build  built on: 2016-01-15 18:54
 powered by Lua 5.1.4 on SDK 1.4.0
MAC:    18:fe:34:d4:c2:b6
Chip:   13943478
Heap:   31832
Web server created

**Comment by mrkale** [comment]
It was a typo in script processing.lua at generating 501 HTTP header. Thank you for notifying. I have pushed the new version 1.5.1.
