### ISSUE TITLE
Error When Web Server starts

### ISSUE THREAD

**Issue by rlust** [mrkale/NodeMCU-WifiDoubleSwitch#3]
I am getting an error in the LUA API call.
Below is my error message and the firmware versions I am running.

 192.168.1.16   255.255.255.0   192.168.1.1

57431 16-02-13 17:30:29 00 0 0 277.0 UTC(NIST) \* 

PANIC: unprotected error in call to Lua API (?:0: attempt to compare nil with number)
�!���1�)m�1�)�!�����

NodeMCU custom build by frightanic.com
    branch: master
    commit: c8037568571edb5c568c2f8231e4f8ce0683b883
    SSL: false
    modules: dht,enduser_setup,file,gpio,i2c,mqtt,net,node,ow,tmr,uart,wifi,ws2812
 build  built on: 2016-02-13 14:04
 powered by Lua 5.1.4 on SDK 1.4.0

**Comment by mrkale** [comment]
This is certainly related to the [issue](https://github.com/mrkale/NodeMCU-Modules/issues/1) in another repository [NodeMCU-Modules](https://github.com/mrkale/NodeMCU-Modules).
