### ISSUE TITLE
ESP8266-v1-> i2c-> MCP23008 switch(8ports)x8units=64ports - NODEMCU

### ISSUE THREAD

**Issue by icyhoty2k** [mrkale/NodeMCU-WifiDoubleSwitch#4]
Can someone help with that

**Comment by mrkale** [comment]
It is not an issue, just a new feature requested. Just fork the project and rewrite processing part of it on your own.

**Comment by icyhoty2k** [comment]
Hello can we arrange a skype meeting i want to aky you some questions ? i
can pay you
question about your program wifi double relay esp8266

**Comment by mrkale** [comment]
I do not use Skype. I prefer email conversation. Please, use the Github issue section for bugs report only. What problem do you have? Have you tried the branch ESP8266-01 or release with tag v1.6.1e?

**Comment by icyhoty2k** [comment]
i have managed to start the program ... now i want to modify it and i need
help.
i also need some info on the program and have questions
1.i need to read form local css file not internet one
2.i need to make it work with mcp 23008

**Comment by mrkale** [comment]
You had better to raise that question in some community, e.g., Google Plus
for ESP8266 (https://plus.google.com/communities/106241547232040808753).
Your request is totally not related to my project. Please do not load the
issue log with unrelated stuff.

**Comment by icyhoty2k** [comment]
ok .. can you tell me then how to read form local css file instead of http
file

**Comment by mrkale** [comment]
Look in the documentation, here for file module in
http://nodemcu.readthedocs.io/en/dev/en/modules/file/#fileread
http://nodemcu.readthedocs.io/en/dev/en/modules/file/
.

**Comment by icyhoty2k** [comment]
no no i mean this:
<link rel="stylesheet"
*href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
<https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css>"*>
i need this thef to be in the internal esp8266 memory , something like this

<link rel="stylesheet" *href="style.css"*>     , but i cannot make it read
the internal style.css :( with that

**Comment by icyhoty2k** [comment]
hello can you answer me how to make the program to read sytle.css trom
esp8266 memory , not internet ?

**Comment by mrkale** [comment]
Not from the head. Study HTML.

**Comment by icyhoty2k** [comment]
ok inline css... or body css .. ok .. .now your progra has a problem that i
cannot use larger stringSize example:limitString=9000 for example

**Comment by icyhoty2k** [comment]
MAC: 5c:cf:7f:07:60:03
Chip: 483331
Heap: 22096
192.168.0.99 255.255.255.0 192.168.0.1
Web server created

> No pin state
> PANIC: unprotected error in call to Lua API (?:0: string length overflow)
> c_ЗПRSцfJSъfJГи
